# Generated by Django 4.2.26 on 2025-11-19 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CabinaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(unique=True)),
                ('tipo', models.CharField(choices=[('BASICA', 'BASICA'), ('GAMER', 'GAMER'), ('VIP', 'VIP')], max_length=16)),
                ('estado', models.CharField(choices=[('DISPONIBLE', 'DISPONIBLE'), ('OCUPADA', 'OCUPADA'), ('MANTENIMIENTO', 'MANTENIMIENTO'), ('DESACTIVADA', 'DESACTIVADA')], default='DISPONIBLE', max_length=16)),
                ('especificaciones', models.JSONField(blank=True, default=dict)),
                ('precio_por_hora', models.DecimalField(decimal_places=2, max_digits=8)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cabinas',
                'ordering': ['numero'],
            },
        ),
    ]
