# Generated by Django 4.2.26 on 2025-11-20 00:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('persistence', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora_inicio', models.DateTimeField()),
                ('fecha_hora_fin', models.DateTimeField()),
                ('estado', models.CharField(choices=[('pendiente', 'pendiente'), ('confirmada', 'confirmada'), ('en_curso', 'en_curso'), ('completada', 'completada'), ('cancelada', 'cancelada')], default='pendiente', max_length=16)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('cabina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='persistence.cabinamodel')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reservas',
                'ordering': ['-creada_en'],
            },
        ),
        migrations.CreateModel(
            name='SesionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora_inicio', models.DateTimeField()),
                ('fecha_hora_fin', models.DateTimeField(blank=True, null=True)),
                ('tiempo_total_minutos', models.PositiveIntegerField(default=0)),
                ('costo_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('precio_por_hora', models.DecimalField(decimal_places=2, max_digits=8)),
                ('estado', models.CharField(choices=[('activa', 'activa'), ('pausada', 'pausada'), ('finalizada', 'finalizada'), ('cancelada', 'cancelada')], default='activa', max_length=16)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('cabina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones', to='persistence.cabinamodel')),
                ('reserva', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sesion', to='persistence.reservamodel')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sesiones',
                'ordering': ['-creado_en'],
                'indexes': [models.Index(fields=['usuario', 'estado'], name='sesiones_usuario_c951e8_idx'), models.Index(fields=['cabina', 'estado'], name='sesiones_cabina__745642_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='reservamodel',
            index=models.Index(fields=['cabina', 'fecha_hora_inicio', 'fecha_hora_fin'], name='reservas_cabina__de38c1_idx'),
        ),
        migrations.AddIndex(
            model_name='reservamodel',
            index=models.Index(fields=['usuario', 'estado'], name='reservas_usuario_2844a8_idx'),
        ),
    ]
