# Generated by Django 4.2.26 on 2025-11-20 00:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('persistence', '0002_reservamodel_sesionmodel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metodo_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta'), ('transferencia', 'Transferencia'), ('billetera_digital', 'Billetera Digital')], max_length=20)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('completado', 'Completado'), ('fallido', 'Fallido'), ('reembolsado', 'Reembolsado')], default='pendiente', max_length=20)),
                ('fecha_pago', models.DateTimeField()),
                ('comprobante_numero', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('notas', models.TextField(blank=True, default='')),
                ('sesion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pago', to='persistence.sesionmodel')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pagos',
                'ordering': ['-fecha_pago'],
                'indexes': [models.Index(fields=['usuario', 'estado'], name='pagos_usuario_ff9803_idx'), models.Index(fields=['fecha_pago'], name='pagos_fecha_p_8536b9_idx'), models.Index(fields=['comprobante_numero'], name='pagos_comprob_bd358f_idx')],
            },
        ),
    ]
